console.log("Hello, World!");
var x = 15;
var y = 10;
console.log("The value of x is: " + x);
console.log("The value of y is: " + y);
console.log("The sum of x and y is: " + (x + y));
console.log("The difference of x and y is: " + (x - y));
console.log("The product of x and y is: " + (x * y));
console.log("The quotient of x and y is: " + (x / y));
console.log("The remainder of x divided by y is: " + (x % y));